/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ZiO8Qzh4YXL
 */
"use client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { signup } from "@/app/newsletter-signup-action";
import { JSX, SVGProps } from "react";
import { useState } from "react";

export function NewsletterSignup() {
  const [email, setEmail] = useState("");
  const [signedUp, setSignedUp] = useState(false);
  const [signedUpFailed, setSignedUpFailed] = useState(false);
  const [signinUp, setSigninUp] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSigninUp(true);
    // Call signup action here
    const singupResponse = await signup(email);
    if (!singupResponse.success) {
      setSignedUpFailed(true);
      setSigninUp(false);
      return;
    }
    setSignedUp(true);
    setSigninUp(false);

    // Clear the form
    setEmail("");
  };
  return (
    <main
      key="1"
      className="min-h-screen bg-gray-900 text-white py-12 px-4 md:px-6 lg:px-8 flex items-center justify-center"
    >
      <div className="max-w-3xl mx-auto">
        <div className="text-center space-y-8">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight">
            Nerdete nyhetsbrev fra Øyvind?
          </h1>
          <p className="text-lg sm:text-xl lg:text-2xl text-gray-500">
            Skal det være noe nerdete greier til random tidspunkt på epost?
            F.eks om DevSecOps, Serverless, .NET, TypeScript, React, Azure,
            Ultraløping, AI, XAI, GenAI, AGI, osv?
          </p>
          <p className="text-lg sm:text-xl lg:text-2xl text-gray-500">
            Om du våger er det bare å skrive inn eposten din her:
          </p>

          <form className="flex space-x-4" onSubmit={handleSubmit}>
            <Input
              className="flex-grow text-black bg-gray-700 px-4 py-2 rounded-md"
              placeholder="Skriv inn eposten din her"
              name="email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
            <Button
              disabled={signinUp}
              className="bg-purple-700 hover:bg-purple-600 transition-colors px-4 py-2 rounded-md text-white"
              type="submit"
            >
              Abonner
            </Button>
          </form>
          {(!signedUpFailed && !signedUp) && (<p className="text-sm sm:text-base lg:text-lg text-gray-500">
            Noen ganger holder det ikke med en LinkedIn post..?
          </p>)}
          {signedUp && (
            <p className="text-sm sm:text-base lg:text-lg text-green-300">
              Skøy, takk!
            </p>
          )}
          {signedUpFailed && (
            <p className="text-sm sm:text-base lg:text-lg text-rose-600">
              Der var du registert fra før av, gitt 👨‍💻
            </p>
          )}

          
          <div className="flex justify-center space-x-4">
            <Button
              className="text-gray-500 hover:text-gray-400 transition-colors"
              variant="link"
            >
              <Link
                className="flex items-center space-x-2"
                href="https://twitter.com/zoney"
              >
                <GlobeIcon className="w-4 h-4" />
                <span>X.com/Zoney</span>
              </Link>
            </Button>
            <Button
              className="text-gray-500 hover:text-gray-400 transition-colors"
              variant="link"
            >
              <Link
                className="flex items-center space-x-2"
                href="https://www.linkedin.com/in/%C3%B8yvind-brekkhus-sand%C3%A5ker-343a0a9/"
              >
                <LinkedinIcon className="w-4 h-4" />
                <span>LinkedIn.com/Øyvind</span>
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </main>
  );
}

function GlobeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>Globe Icon</title>
      <circle cx="12" cy="12" r="10" />
      <line x1="2" x2="22" y1="12" y2="12" />
      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
    </svg>
  );
}

function LinkedinIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <title>LinkedIn Icon</title>
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}
